### ISSUE TITLE
parallel faults 

### ISSUE THREAD

**Issue by cfandel** [gempy-project/gempy#200]
**Describe the bug**
When adding faults with GemPy,  one fault or two intersecting faults work OK, but when I try to have two roughly parallel finite faults, they behave very strangely and affect each other when they shouldn't.

**To Reproduce**
See jupyter notebook here: https://github.com/cfandel/gottesacker/blob/master/faults.ipynb
There are two fault families in the data: A and B. 
To turn different faults on and off, change the faults listed in `faultNames`.
If one fault from each family is included (faultNames = ['faultA1', 'faultB1']), the faults behave normally.
If two faults from the same family are included (faultNames = ['faultA1', 'faultB1'], the faults look very weird. Need to visualize them in the 3D VTK viewer to see them properly.

Currently, each fault is represented by 5 points: four interface points defining the extent of the ellipse (one on each end, one on top, one on bottom), plus one orientation point at the center. The faults are all vertical (dipping 90 degrees).

**Expected behavior**
Faults from the same family are roughly parallel and should not interact with each other. 
Would it work to put all faults of the same family into one series?

**Comment by Leguark** [comment]
That is definitely not implemented and I should put an assert somewhere so people do not try to do so  (#201)

What you want to is doable but it is a couple of days work  and I am not sure how useful is to have faults that cannot intersect each other anywhere. Usually listric faults end up converging, dont they?

**Comment by cfandel** [comment]
Ah OK good to know.
In this case it is actually pretty important because there are two major NE-trending faults in the area, each of which has a significant vertical offset, but they don't converge (the system is too shallow for them to be listric). If it's possible to implement that would be very helpful!

**Comment by Leguark** [comment]
It is possible but not too easy. Just keep me posted if the lack of the feature completely screw your model I will push it up on the priority list :)

**Comment by cfandel** [comment]
OK thanks - it would be really helpful, since right now I am stuck modelling one of the faul offsets as a fold, which isn't accurate. I would guess also that other people will want this feature, since a lot of systems have parallel faulting that doesn't necessarily converge at depth.

**Comment by bistek** [comment]
Hello, the possibility to model parallel faults is fundamental!
Thanks!
