### ISSUE TITLE
Orientation with no surface constraint and other structural constraints

### ISSUE THREAD

**Issue by andrea-bistacchi** [gempy-project/gempy#224]
Hello, first a question:

- When you specify an orientation associated to a given stratigraphic unit, you mean you are **exactly** at that stratigraphic level (i.e. on the base boundary of the unit) or **within** the unit (i.e. between the base of the unit and the base of the overlying unit)?

In any case the feature request are for:

- Constraints where you specify the orientation (i.e. the gradient of the stratigraphic potential field) but not the stratigraphic unit (hence not the value of the stratigraphic potential field). This would be useful in many situations starting from field or subsurface input data.

- Constraints where you specify some value related to the potential field gradient - for instance the scalar o cross product of the gradient with some vector. This would open the door to using more advanced structural constraints like fro instance fold axes or fold axial planes.

Maybe there is already a way to do this using directly the gradient? Which function should I try to use?

Thanks very much!

**Comment by Leguark** [comment]
Orientations can be placed anywhere in space. They are "series" dependent and not "surface" dependent. Right now, they are associated to stratigraphic units only for color reasons (ideally we would have a main color for each series and each surface would be related to that main color somehow but we did not find a good way to do it if you have 10 series).

Now, for the type of constrains you mention one aspect we did not have time to explore much is to vary the module of the orientations. You can play with it by changing the value of polarity on the dataframe. Having a clever way to control the module of orientations depending where are located respect fold axis could be interesting!
