### ISSUE TITLE
provide sanity check on computational requirements

### ISSUE THREAD

**Issue by AndrewAnnex** [gempy-project/gempy#231]
**Is your feature request related to a problem? Please describe.**
While experimenting with gempy, I am starting to develop a sense of how much memory and compute time a given model computation will take but it is a very slow process. 

**Describe the solution you'd like**
A helper function to give the users a sanity check for the assembled model to tell the user if they are asking too much of the available compute resources/time. Ie if the model would over-allocate the system or GPU memory, it would be helpful to know so. It would also be great if the sanity check provided some feedback depending on the user-provided data like "your topography is too big, reduce it to be no bigger than X" or "you provided too many surface points, reduce to no more than X" etc. 

Alternatively, a simpler function could just provide the relevant numbers for the various parameters of concern, and the documentation could be updated to include feedback for each parameter that the user could lookup (ie if you have more than X surface points do Y) or something like that.

**Describe alternatives you've considered**
changing stuff and seeing what happens...

**Comment by AndrewAnnex** [comment]
found https://github.com/cgre-aachen/gempy/issues/123, looks like a good option to add to the docs

**Comment by Leguark** [comment]
yes, that is a great idea. The problem is that is not easy to give exact number because is too coupled but at least I could rise a bunch of warnings.

My comment #123 is quite ad-hoc explanation but it may work. We really need to rework the tutorials to something more cohesive at some point but maybe I can add at least that in the tutorial of the fundamentals
