### ISSUE TITLE
Finite Element mesh from GemPy model

### ISSUE THREAD

**Issue by nlosacco** [gempy-project/gempy#250]
I am trying to build a Finite Element mesh from the geological model I have created with GemPy. Where can I find info on how to do it?
An option would be exporting the surfaces (as NURBS) or the enclosed volumes as geometric entities and the importing them in a FE preprocessor.

**Comment by Leguark** [comment]
Sorry for the late response. Thank you for the hints! Adding NURBs and a better integration with cgal are things we keep in mind.

At the moment we do not have a supported way to create a water tight mesh from a gempy model. One relative easy way to get a first export would be to use the voxels of a regular grid.

 Please let us know if you get any progress or we can help!
