### ISSUE TITLE
Port to TensorFlow

### ISSUE THREAD

**Issue by agzimmerman** [gempy-project/gempy#274]
**Is your feature request related to a problem? Please describe.**
At the moment Gempy is developed on Theano to do kriging to generate the scaler field. As Theano has been stopped developing since 2017, and Tensorflow has become a more popular and easier for debugging tool for auto-differentiation and been actively supported, there is a good reason to switch the core interpolation part of Gempy to Tensorflow.

**Describe the solution you'd like**
Implement the co-Kriging part used to interpolate the scaler filed in Tensorlfow and integrated with Gempy main software.

**Describe alternatives you've considered**
Jax and Pytorch are also possible to be tested

**Additional context**
the second derivative of the posterior

**Comment by alexanderzimmerman** [comment]
None of this will be merged for 2.1. Highest priority for 2.2 is having on scalar field. More complex models will come in later versions.

**Comment by alexanderzimmerman** [comment]
What work is remaining here? @GeorgeLiang3 , could you edit the original issue description? Right now it has only the default text from the issue template.

**Comment by alexanderzimmerman** [comment]
Thanks for editing the description, @GeorgeLiang3 .

Why did you mention the second derivative of the posterior? Is this needed for co-Kriging? Is it unclear how to obtain it with TensorFlow?

**Comment by AndrewAnnex** [comment]
I posted this in the software underground slack but there are other frameworks to consider including kepos (https://www.kernel-operations.io/keops/index.html) that seem to scale better with larger datasets. I think for now continue as planned, and by refactoring the code to TensorFlow it may make some of the underlying code clearer and easier to abstract to different implementations

**Comment by istrous** [comment]
hi,@agzimmerman,When do you plan to move to TensorFlow or Pytorch from theano?

**Comment by istrous** [comment]
hi,@agzimmerman, Is there a plan to migrate to TensorFlow or Pytorch?

**Comment by AlexanderJuestel** [comment]
@istrous a implementation using aesara is currently under development and will be released shortly. This release should also solve many other dependency issues.

Cheers
Alex

**Comment by istrous** [comment]
@agzimmerman ，That's great，Thanks

**Comment by agzimmerman** [comment]
Hey @istrous I just noticed that you have accidentally been tagging me instead of @AlexanderJuestel :)

**Comment by Japhiolite** [comment]
@istrous see here: https://github.com/GeorgeLiang3/GemPyTF

**Comment by Leguark** [comment]
We ported it to PyTorch one week after finish the TF. TF is deprecated before being born.

Congrats!
