### ISSUE TITLE
Finite element mesh generator

### ISSUE THREAD

**Issue by agzimmerman** [gempy-project/gempy#275]
**Is your feature request related to a problem? Please describe.**
Problem: FE-meshes facilitate better representation of structural features in a geological model, such as faults. As these are of particular interest for potential process simulation (e.g. fluid flow) in a geological model, precise representation of these features in the mesh is important.     

**Describe the solution you'd like**
Ideal: implement/attach a high-level python wrapper for one of the existing meshing codes (CGAL, Tetgen, Gmesh) to Gempy for facilitating mesh generation (analogue to the current hexahedral grid)

**Describe alternatives you've considered**
n/a

**Additional context**
We are very enthusiastic about making 3D tetrahedral meshes inside closed surfaces, improving the techniques of it and finally use it inside the gempy. Not only for calculation of deformation by FEM but also for other necessaries of 3D meshes in geological modeling. 

We'd like to use some famous engines to reach this goal. If they are based on c++ code, we want to use some python wrapper to use these engines very fast. Right now, they are some famous options we'd like to use: CGAL, Tetgen and Gmesh.

**Comment by Japhiolite** [comment]
This is also related to Issue #250

**Comment by egallyamov** [comment]
Hello,
Could you give an update on the current status of this development? 
Regards,
Emil

**Comment by Japhiolite** [comment]
Hi Emil,

there hasn't been much development on this topic.

Best,
Jan
