### ISSUE TITLE
Vertical Exaggeration for gp.plot.plot_scalar_field(...) missing

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#313]
**Is your feature request related to a problem? Please describe.**
When plotting long but shallow profiles (in my case right now 15,000 m long and 300 m deep), the vertical exaggeration of the scalar field can not be adjusted when calling `gp.plot.plot_scalar_field(...)`. The plot does not look very nice.

**Describe the solution you'd like**
It would be nice to have a variable `ve = ` to adjust the vertical exaggeration similar to `gp.plot.plot_section(...)`.

**Describe alternatives you've considered**
A workaround could be to adjust the plot with the functionality of Matplotlib manually.

![image](https://user-images.githubusercontent.com/45469915/75754533-30b06700-5d2d-11ea-8179-af403be35466.png)

**Comment by AlexanderJuestel** [comment]
> Yes, we need to fix this but until we implement anisotropy I recommend you to multiply the Z coordinates of all your input data by a factor of 4 or 5 (making it more "boxy"). Otherwise, the interpolator is going to have problems too.

**Comment by AlexanderJuestel** [comment]
Just remember to also multiply the Z values of the topography then `topo.values[:,2] = topo.values[:,2]*5`

**Comment by pytzcarraldo** [comment]
Wouldn't using the `aspect` keyword of `plt.imshow` do the trick? for the sections at least
