### ISSUE TITLE
Activating/Deactivating data

### ISSUE THREAD

**Issue by Leguark** [gempy-project/gempy#365]
**Is your feature request related to a problem? Please describe.**
At the moment the only way to edit the models is by completely adding/removing data from the correspondent dataframes. In many cases, we will just want to deactivate it temporary to see how the model would change.  

**Describe the solution you'd like**
We should have a boolean 'isActive' column in the series-surfaces-surface points -orientation data frame. This column will be used to filter any type of data whenever we query it.

It is important that they are in sync i.e. If a surface 'isActive' is set to False, all the surface points and orientations belonging to that surface must be also set False. 

**Additional context**
- For series and surfaces the column 'isActive' already exist but is only dependent on the existence of data points. For example, a series with no surfaces assigned will be inactive ('isActive' -> False).

- This is the first step towards hierarchical modelling gempy-project/gempy_engine#4 . Different levels will be sampled by similar boolean logic

**Comment by AlexanderJuestel** [comment]
That is a great idea since I am adding my data stepwise to the models as well. One thing you may want to consider is also sampling the available data. Especially if you have vector data from geological maps (vertices of layer boundaries) there is always the need to simplify or reduce the amount of data points, especially if you have very curvey faults or layer boundaries.

**Comment by WestfalNamur** [comment]
Could you have one open data frame with a column ACTIVE that the user can interact with and one that is private and a function of the public one? This one would just consist of the ACTIVE == True data rows?

**Comment by AndrewAnnex** [comment]
@AlexanderJuestel, that is something I have been dealing with, primarily externally from gempy's perspective by using imblearn and resampling data points along contacts within QGIS. But of a collection of utilities to deal with data imbalance and spatial rebalancing could be an issue/library unto iteself.

**Comment by AlexanderJuestel** [comment]
Hey @Leguark,

this could be a nice feature for GemGIS, would you mind if we take care of that? Then I will transfer it to our issues :) 

Cheers Alex
