### ISSUE TITLE
Procedural terrain generation

### ISSUE THREAD

**Issue by flohorovicic** [gempy-project/gempy#366]
**Is your feature request related to a problem? Please describe.**
Random topography generation using fractal methods is a bit 80's... nice for mathematical reasons, but not really realistic. 

**Describe the solution you'd like**
Procedural landscape generation, e.g. the simple Diamond-Square algorithm: 
- http://jmecom.github.io/blog/2015/diamond-square/
- https://github.com/buckinha/DiamondSquare

**Describe alternatives you've considered**
n/a

**Additional context**
Many more methods for terrain generation exist (mostly for computer games), this seems to be an interesting overview (but paywalled and I couldn't get access):
https://link.springer.com/chapter/10.1007/978-3-030-21077-9_6

**Comment by flohorovicic** [comment]
Example in commit bf51f9a

**Comment by Leguark** [comment]
This looks really cool. The whole topography grid needs a refresh once you finish you Epic. At the moment is not as modular as it could be and relays unnecessarily on gdal

**Comment by flohorovicic** [comment]
Just a quick update (if anyone is interested): resulted in a development branch (latest commit: f0163ce4701f9b688de140ae379f0babc84d20fc) - mostly focussing on a vectorised implementation of the D-S algorithm at the moment. But a lot of interesting stuff that could be done.

**Comment by AlexanderJuestel** [comment]
@flohorovicic what would you think about adding this feature to GemGIS?
