### ISSUE TITLE
Align 2D plot at surface

### ISSUE THREAD

**Issue by domist07** [gempy-project/gempy#389]
In order to be able to analyze the course of the layer more easily, it would be useful to align the upper or lower border of the surface to a constant height as in the example pictures:
![Align_Surface1](https://user-images.githubusercontent.com/59735059/79958799-a611fb80-8483-11ea-8a84-150d3a07a6fd.jpg)
Aligned to Surface 1
![Align_Surface2](https://user-images.githubusercontent.com/59735059/79958803-a6aa9200-8483-11ea-8a1e-15b117ecb031.jpg)
Aligned to Surface 2

As reference the current status:
![Align_Absolute](https://user-images.githubusercontent.com/59735059/79958795-a5796500-8483-11ea-95cf-9d3468ba32f6.jpg)

**Comment by flohorovicic** [comment]
Interesting - so just to understand, transform the model to fit to a reference surface? Seems very much related to balancing approaches. Not yet implemented, and probably difficult to generalise - but for (relatively) simple 2.5-D setting (as in your examples above), I think this could be (a) possible, and (b) maybe even relatively easy to implement. Possibilities:

- vertical projection (vertical thickness), should be straight-forward
- projection according to scalar field of reference surface (similar to developments of @javoha )

**Comment by domist07** [comment]
Yes, where the target surface is a horizontal plane.
I also think that in 3D it will be much difficult, but in 2.5D it will be a nice feature.
