### ISSUE TITLE
Surfaces don't mask each other

### ISSUE THREAD

**Issue by domist07** [gempy-project/gempy#400]
**Describe the bug**
The surfaces don't mask each other instead I have installed the scikit-image version of Leguark as described in #216. I only get the warning "WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions." when executing GemPy, but I think thats not relevant for the problem. The warning "UserWarning: Surfaces not computed due to: marching_cubes_lewiner() got an unexpected keyword argument 'mask' " **doesn't** arrises.

**Desktop**
  * System: Ubuntu 19.10 as Virtual machine on Windows 10
  * GemPy version 2.1.1

**To Reproduce**
Today I run these two installation commands:
```
pip3 install git+git://github.com/Leguark/scikit-image@master
pip3 install gempy
```
Then I load my model, set the relations, calculate the surfaces and plot it:
```
[...] # loading data and set relations
gp.compute_model(geo_data, sort_surfaces=False, compute_mesh=True, debug=False)
gv = vista.Vista(geo_data, plotter_type='background', notebook=False, real_time=False)
gv.plot_surfaces()
```

**Expected behavior**
The blue surface has an onlap relation according to the red surface and should be cut off by it.

**Screenshots**
![Bildschirmfoto vom 2020-04-27 12-05-42](https://user-images.githubusercontent.com/59735059/80404548-a403ce80-88c1-11ea-88bb-e4264f7c006a.png)

**Comment by javoha** [comment]
Hi @domist07 ,
is it correct though that you get the "correct" behavior when plotting the lithology block model (e.g. in a cross section?). If I rememebr correctly that is the case and that means we "just"have to fix the marching cubes ...
Thanks for pointing this out!

**Comment by domist07** [comment]
Yes the lithology block model is correct, but the contact lines aren't cut off too.

**Comment by Leguark** [comment]
Were you able to compile scikit image in windows? Can you tell me how?
 I am stuck there at the moment so I can not test it (yes, I feel ashamed 😄 )
In scikit image 0.17 the necessary code comes in the pip installation so I was waiting till then to really support the feature

**Comment by domist07** [comment]
No that's the reason why I run Ubuntu as a virtual machine. All Python files run on Ubuntu and I've the scikit image version 17-dev0, but that doesn't mask the marching cubes.
