### ISSUE TITLE
Plot arbitrary field (as option in 2D and 3D)

### ISSUE THREAD

**Issue by Leguark** [gempy-project/gempy#424]
**Is your feature request related to a problem? Please describe.**
Adding an example passing arbitrary scalar fields to the plot 2d and plot 3d

[ ] If the computation of the gradient of the scalar field -used for the surfaces interpolation- becomes an standard gempy output before this issue is done, we should add the option to directly plotting the gradient too

**Comment by AndrewAnnex** [comment]
I just ran across a use case where it would be very useful for me to have access the the gradient of the scalar field, specifically for custom grids

**Comment by Leguark** [comment]
GemPy v3 has a better implementation of interpolating the gradients. To date there is no API but you can find some tests in gempy_engine
