### ISSUE TITLE
Return Fault Offset along Faults for geological interpretations

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#455]
**Is your feature request related to a problem? Please describe.**
For a geologist, it is necessary to know the fault offset along a fault for one or several layers. This could be important for sealing purposes (see Allen diagram below) or for a general characterization of the model. 

**Describe the solution you'd like**
The offset could be displayed on a particular fault plane (distinguishment between vertical displacement and vector of displacement) but should also be returned as numerical values at certain positions or interface positions?! Or a range could be returned, min-max offset for instance. Also, it would be important to get the offset for each surface as the offset may vary.

![image](https://user-images.githubusercontent.com/45469915/85413636-5c20c100-b56b-11ea-92bf-c875a130de29.png)
(Image Source: http://www.searchanddiscovery.com/documents/2016/41821yielding/ndx_yielding.pdf)

**Comment by Japhiolite** [comment]
If I'm not mistaken, I think the topological graphs or Fabian's work in his thesis could be useful for this.

**Comment by alex-schaaf** [comment]
Yeah didn't @fastamo implement some Alan diagram-style thing? 🤔

**Comment by fastamo** [comment]
Yep, I had created a "fault_analysis" module for that. It wasn't super accurate, but you could generate such fault-plane sections based on voxel resolution, and then also return the offset. But I can't find the module in assets or anywhere else.

**Comment by alex-schaaf** [comment]
Yeah, you'd probably have to recover it from older commits - and it probably needs quite some fixing to work with the current geomigueller

**Comment by fastamo** [comment]
Probably. I had done that for GemPy 1.X
