### ISSUE TITLE
deviation in the CenteredGrid

### ISSUE THREAD

**Issue by GeorgeLiang3** [gempy-project/gempy#578]
**Describe the bug**
In Tutorial 2.2: Centered Grid, the centers of the grid are not at the centers, instead, the left and right points are at the midpoints of two adjacent center points. In addition, the resolution and the radius at the moment are actually extended further, which might cause confusion to the users. 

**Expected behavior**
So what's originally designed here is the grid centers grow exponentially with respect to the radius. The problem comes from computing the left and right points, where we find the midpoint of the two adjacent centers as the boundary point. However, this will 1) require extending the grids further than what given by the user, e.g. the radius is given by the user is 100, the left-most center is placed at -100, the left side boundary is -100-(grid size). What I think should be better, is to define the left-right sides as the exponential factor, and find the center points. This will keep the resolution and radius provided by the user and also fix the plotting in the example.

**Screenshots**
![image](https://user-images.githubusercontent.com/42550795/109658602-bf0a3380-7ba1-11eb-80d7-3788226b7547.png)

**Desktop (please complete the following information):**
  * OS: MacOS
  * GemPy Version
    * if cloned from GitHub: provide Git commit id 7085198
  * Jupyter Version (if applicable)

**Additional context**

**Comment by Leguark** [comment]
I will merge the pull request later today. I close the issue. Thanks George!
