### ISSUE TITLE
Gradient arrow not rotated when changing vertical exxagaration in 3D view

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#627]
**Describe the bug**
Gradient arrows are not scaled in 3D view

**To Reproduce**
Create model and change `ve`

**Expected behavior**
Arrows should be scaled/rotated when changing `ve`

**Screenshots**

ve=1, correct rotation
![image](https://user-images.githubusercontent.com/45469915/126443008-7af775d1-f997-4e6c-847b-d3ca11d1cb85.png)

ve=3, arrow not rotated
![image](https://user-images.githubusercontent.com/45469915/126443129-221ce27c-6d6f-43a5-bd7d-75c8c0d5ecb5.png)

**Comment by Leguark** [comment]
This is a very tricky problem. We solved it in LiquidEarth, if it becomes a recurrent issue we can port it to GemPy but it is not a simple fix
