### ISSUE TITLE
Create one mesh per stratigraphic unit per fault block

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#671]
**Is your feature request related to a problem? Please describe.**
For our projects, we need to extract depth information from the meshes created in GemPy. This works so far so good if you do not have thrusted layers. If you have thrusted layers, isolines cannot be calculated for that mesh properly.

**Describe the solution you'd like**
Calculate and return one mesh per stratigraphic unit per fault block and return those for future processing

**Describe alternatives you've considered**
I currently limit the meshes using the pyvista `clip_surface` function, extract the vertices, load these as CSV in QGIS, remove some odd values, export the points, load them in another software to remove the artifacts caused by the thrusts, calculate a new surface based on the remaining points and export as ZMAP to load in QGIS again. 

Image: Faults in red, artifacts of thursts that need to be removed and the layer in the center that I need
![image](https://user-images.githubusercontent.com/45469915/154957644-09d703ac-057b-497f-a4c1-a0851a8f706e.png)

**Comment by Leguark** [comment]
In GemPy v3 there is one vertex by voxel. Hopefully will make easier this type of operations. For now I close it if it is not urgent
