### ISSUE TITLE
Error building Docker Image

### ISSUE THREAD

**Issue by snakesonabrain** [gempy-project/gempy#684]
Hi,

Because I had some issues with the installation process in MacOS, I tried building the Docker image myself from the dockerfile. However, the build failed with the following message:

Could not find a version that satisfies the requirement PyQt5-Qt5>=5.15.2 (from pyqt5->gempy) (from versions: )
#13 64.50 No matching distribution found for PyQt5-Qt5>=5.15.2 (from pyqt5->gempy)

I tried to use the leguark/gempy image but ran into some errors there too (see issue on [dead Kernel with plot_3D](https://github.com/cgre-aachen/gempy/issues/680)).

**Comment by Japhiolite** [comment]
Hi @snakesonabrain 

for Mac, I have this gempy environment. I use it on my machine and currently working with also 3D plotting.
https://github.com/Japhiolite/environments/blob/master/environment_gempy_mac2.yml

**Comment by Japhiolite** [comment]
Hi @snakesonabrain 

can you link to Miguels docker image? could not find a leguark/gempy repository.

**Comment by snakesonabrain** [comment]
> Hi @snakesonabrain
> 
> can you link to Miguels docker image? could not find a leguark/gempy repository.

Where can I find this Docker image? The leguark/gempy image is the once which is mentioned in the installation guide.

**Comment by Japhiolite** [comment]
Ah, I see. Thought you were trying the docker image. 
That might be a remnant in the documentation and the docker may (most likely will) not be up to date, if it still exists. I'll ask @Leguark .

**Comment by Japhiolite** [comment]
> 

Hi @snakesonabrain 
the docker image can be found here: https://hub.docker.com/r/leguark/gempy
However, it might not work as it's pretty old...but maybe I'm mistaken and it works after all :)

**Comment by snakesonabrain** [comment]
> 

Tried that one, but it returns an error when running the getting started jupyter notebook:

[Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running](https://stackoverflow.com/questions/56129786/cannot-load-backend-qt5agg-which-requires-the-qt5-interactive-framework-as)

**Comment by Japhiolite** [comment]
Just to clarify, you try running gempy in a jupyter notebook (and not, for instance, google colab) on which OS?

**Comment by snakesonabrain** [comment]
Indeed, just a local Jupyter notebook, opened from the Docker console. But it is the same issue.

**Comment by snakesonabrain** [comment]
I have tried the docker image on another PC with Windows 10 as OS and it gives exactly the same error (as could be expected with Docker). So the image by @Leguark likely needs checking.

**Comment by Leguark** [comment]
Docker is not supported anymore. We have axed most of gempy dependencies so hopefully we never need to go through the "add complexity" route to deal with complexity
