### ISSUE TITLE
The number of surface points is inconsistent with the number of geo_model.solutions.block_at_surface_points

### ISSUE THREAD

**Issue by Linya-Peng** [gempy-project/gempy#702]
**What is your question?**
Hi~
I am using get_started.ipynb for a simple test. In this example, we have **8 surface points**, 
![image](https://user-images.githubusercontent.com/61902717/173275395-69bb3bd4-6955-4221-b1fe-34b77edf1e22.png)
![image](https://user-images.githubusercontent.com/61902717/173275464-e293a71f-4cb7-4e2b-8ed9-b4010e37f3b4.png)

but why does block_at_surface_points (3D array with all interpolated values for a given series and at the interface) have **10 values**?
![image](https://user-images.githubusercontent.com/61902717/173275357-c807df31-f221-48b0-ab3b-0164beba676b.png)

Did I misunderstand something? 
Thank you in advance

**Comment by Leguark** [comment]
I am also a bit puzzle by this. My best guess is that we are not evaluating in the reference point of each surface (one per surface) so then we would have 5 points and then evaluate once per series, i.e. 2 times. Still funny behavior, if it still an issue in GemPy v3 and you want a better explanation let us know
