### ISSUE TITLE
Implementing indicator kriging

### ISSUE THREAD

**Issue by fabiojdf** [gempy-project/gempy#725]
I think that indicator kriging (IK) would be a great feature for gempy. I didn't found it in the documentation neither in the source code. Sequential indicator simulations would be a straightforward implementation after that. By this way, gempy covers both continuous and discrete simulations algorithms.

I guess that the implementation wouldn't be hard. A repo that contains IK implementation can be found on https://github.com/seismicreservoirmodeling/SeReMpy

Kind regards

**Comment by javoha** [comment]
Hi @fabiojdf,
the code for continuous property kriging and simulation in gempy is pretty basic and not very powerful regarding runtime. I wrote some code to use gempy with gstools (https://geostat-framework.readthedocs.io/projects/gstools/en/stable/) for a more optimized runtime. The code is published on Zenodo (https://zenodo.org/record/6327450) with this paper (https://link.springer.com/article/10.1007/s11001-022-09475-z). 
So if you need this you can probably reuse a lot of the code - basically it extracts the 3D grid and coordinates of your gempy model so you can do the Kriging (or Indicator Kringing) with any other package. Afterwards there are some methods to visualize the results with the gempy model.

Maybe this is helpfull.
Best Regards

**Comment by AlexanderJuestel** [comment]
@fabiojdf, is the answer provided by @jahova sufficient?
