### ISSUE TITLE
[ENH] Replcace numpy_to_vtk with pv.convert_array

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#758]
Currently, the `numpy_to_vtk` function is used a couple of times in GemPy. I suggest replacing this with the equivalent function `pv.convert_array` (https://docs.pyvista.org/api/utilities/_autosummary/pyvista.convert_array.html) and to remove the vtk import.

**Comment by Japhiolite** [comment]
maybe. Is there a huge benefit? Cause `pv.convert_array` also uses `numpy_to_vtk` as far as I can tell? And pyvista also relies on vtk, so we cannot ditch that import altogether.

**Comment by AlexanderJuestel** [comment]
`import vtk` will remain, what is removed is the import of that function

**Comment by Leguark** [comment]
I will merge it later today or tomorrow. I close the issue for now. Thanks @AlexanderJuestel
