### ISSUE TITLE
[TEST] FutureWarning in data.py:751

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#766]
**Describe the bug**
Currents tests return a `FutureWarning`  for https://github.com/cgre-aachen/gempy/blob/10d6fff2c01990d88de40851cd4fdb00eb682a5a/gempy/core/data.py#L751-L752

This could be fixed prior to releasing GemPy 2.3.

`  /home/runner/work/gempy/gempy/gempy/core/data.py:751: FutureWarning: The behavior of DataFrame([categorical, ...]) is deprecated and in a future version will be changed to match the behavior of DataFrame([any_listlike, ...]). To retain the old behavior, pass as a dictionary DataFrame({col: categorical, ..})
    new_series_mapping = pn.DataFrame([pn.Categorical(s, self.series.df.index)],`

**Comment by Leguark** [comment]
We do not depend on pandas for basic data structures anymore!
