### ISSUE TITLE
How to use GPU in 'set_interpolator'

### ISSUE THREAD

**Issue by leilin1995** [gempy-project/gempy#791]
**I used the resolution of (256,256,256) in my own modelling session, and I want to accelerate the interpolation process by GPU. What should I do?**
![image](https://user-images.githubusercontent.com/104147030/231751776-87d82147-7f0f-409b-a47b-1751b678ea18.png)

**Comment by javoha** [comment]
Hi, I think this is a little tricky due to the Theano dependency. I havent done it myself and hopefully it will be resolved with a new gempy version moving away from theano. You could try the answer provided here: #147

**Comment by NilsChudalla** [comment]
Hello! If you are using a dedicated GPU with cuda, try

`os.environ["THEANO_FLAGS"] = "mode=FAST_RUN,device=cuda"`

before setting up the interpolator.

**Comment by AlexanderJuestel** [comment]
@leilin1995 do you have any update on your issue? Did the suggestion by @NilsChudalla work for you?

**Comment by Leguark** [comment]
Theano backend is discontinued. In GemPy v3 GPU usage will be exposed in the API in the coming couple of months.
