### ISSUE TITLE
plot_3d Display effect

### ISSUE THREAD

**Issue by cugb-suerwei** [gempy-project/gempy#797]
![236613057-c8cbe6d8-ce1b-4e66-be05-e0b891126a0d](https://github.com/cgre-aachen/gempy/assets/24865219/e18316bd-bfb8-47c0-a1a9-376bd0458483)
![236613239-f751ff2f-1b15-4ae1-930b-17d150455640](https://github.com/cgre-aachen/gempy/assets/24865219/0ff3f00f-2d76-432c-ae5e-8feb6547532e)
I can now run the sample code, but I have encountered another problem. The model I constructed only has faces and no geological bodies. I completely used the data from the sample document, but the results were different.
The above image is the model I built, and the following is the model in the document

I have tried show_lith=true, but it has not worked and the display effect has not changed.
I conducted further testing and found that running the same code on a Linux system can build a body model, but on a Windows system, only a surface model of the stratum can be built.

**Comment by AlexanderJuestel** [comment]
@cugb-suerwei we have updated GemPy to version 2.3. Could you install the new version and see if your error still persists?
