### ISSUE TITLE
Torturial 1.3b isn´t working because of error in section_utils.py (1D-Array is adressed as 2D-Array)

### ISSUE THREAD

**Issue by josua-kaden** [gempy-project/gempy#812]
Hi, 
I'm currently trying to get some sections from my data and tried the Tutorial 1.3b, for this I jsut copied the code from GitHub. Unfortunately i get following error: 

` line 32, in _extract_boundaries    
    a = self.model.solutions.sections[1][:, l0:l1]
IndexError: too many indices for array: array is 1-dimensional, but 2 were 
indexed`

The problem seems to be that the section Values are saved as arrays in a list, but the adressing here seems not correct, which is fixable, however further down the line (line 56), when fixing the line 32 error the addressing is again not correct. So I´m a bit confused if maybe I do something incorrect or there is something else I have overlooked.

Hope the can be fixed, have a nice day.

**Comment by AlexanderJuestel** [comment]
Hey @josua-kaden, 

in which part of the tutorial does the error occur? Is it in the lower "Get polygons of formations in sections" section?

Sorry for getting back to you so late.

**Comment by josua-kaden** [comment]
Hi @AlexanderJuestel ,

no worries. The error occurs when the polygons of the sections should be extracted. It is the line `polygondict, cdict, extent = section_utils.get_polygon_dictionary(geo_model, section_name)` almost the last step in the tutorial.

**Comment by josua-kaden** [comment]
Hi, 
adding to this, the testdata for the simple faults model on your website is linking to a file which contains a comma bevor the header which lead in another instance for me to in index error, if you could just change the link to your current github raw data like: https://raw.githubusercontent.com/cgre-aachen/gempy/main/examples/data/input_data/tut_chapter1/simple_fault_model_orientations.csv . 

This would be great.

**Comment by Leguark** [comment]
This should be fixed in gempy v3
