### ISSUE TITLE
Pyvista editor not changing visualizations

### ISSUE THREAD

**Issue by lucianomarquetto** [gempy-project/gempy#824]
Hi all! Not sure if this is a bug or it is just me. Still would be good to find a solution.

**Describe the bug**
Whenever I use `gp.plot_3d` for input points or the already computed model, I notice I can't use the GUI editor of pyvista. The buttons are there, and I can check or uncheck the visibility and change opacity values, but those do not take effect on the 3D visualization. I am using Pyvista = 0.39.1. All commands/buttons from the pyvista screen work except the ones from the editor window.

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1. For me just trying to plot anything using `gp.plot_3d` causes this.

**Expected behavior**
Being able to change parameters in pyvista editor (hide/show layers, grids, axis).

**Additional information**
I am using pyvista version == 0.39.1. Tried to update it to 0.41.1 but did not solve the problem. Also, when I plot the 3D visualisation, it starts with those weird big numbers on the axis:
![image](https://github.com/cgre-aachen/gempy/assets/103533248/99b700e0-59a1-4471-a45d-a548eb23d9a5)

Then when I add bounds grid (back) this goes back to normal:
![image](https://github.com/cgre-aachen/gempy/assets/103533248/eb5674b0-2f4c-4725-a837-e1b522766f87)

**Desktop (please complete the following information):**
OS: Ubuntu 22.04 Jammy Jellyfish
GemPy Version: 2.3.1
Jupyter Version (if applicable): 4.0.5 (installed with conda)

**Comment by AlexanderJuestel** [comment]
@lucianomarquetto are you using the trame backend inside a Jupyter Notebook or PyVista in an external window?

**Comment by lucianomarquetto** [comment]
Hi @AlexanderJuestel , I am using Pyvista in an external window. E.g.: 

`gp.plot_3d(geo_model, notebook=False, ve=200, plotter_type='background', show_topography=False, show_data=False)`

Cheers!

Luciano

**Comment by lucianomarquetto** [comment]
By the way, I could plot using Trame (just discovered it was possible with your message!) using `gp.plot_3d(geo_model, ve=10, notebook = True, show_topography=False)` after installing Trame and all its stuff. I still get those big numbers and when toggling ruler off and on again they get back to normal number size:

![image](https://github.com/cgre-aachen/gempy/assets/103533248/7637c41d-0e7e-41b6-b067-2ac661000273)

![image](https://github.com/cgre-aachen/gempy/assets/103533248/fc85901c-e94f-41d6-82ee-2e6ebf45a8b3)

The only thing is that I can't hide and show different layers, so would still be good to find what is the problem with the editor in an external window.

Cheers!
