### ISSUE TITLE
Problems exporting flac3D .f3grid file format

### ISSUE THREAD

**Issue by nearfuture625** [gempy-project/gempy#837]
Hi all,

Thank you for developing such a useful software as Gempy, which allowed me to model a four-layer geological formation with two faults. I noticed that f3grid mesh files that can be used in FLAC3D can be exported via export.export_flac3D_input (geo_model, path='', filename='') in gempy.However, after exporting to f3grid file, I found that the mesh file does not contain a fault structure, please tell me how to export the mesh file related to the fault

![54ab4b681d4e2a61efcccf0354bb1c5](https://github.com/cgre-aachen/gempy/assets/145415488/492090fe-48fb-4c3c-93dd-eafe51c0af17)
Looking forward to your answer

**Comment by MoiseRousseau** [comment]
@nearfuture625: Let's talk here about this problem and the other you send me and related to exporting to FLAC3D 6.00 (https://github.com/MoiseRousseau/Variational-Tet-Mesh/issues/1).

1. For instance, only the block mesh are exported, and there is not current code (from my side at least) to export the fault zone. Doing so would requires to adapt the mesh to the fault and export the face groups, or to create kind of a new material and export it as a fault zone.
2. It seems you successfully export a mesh and reimport in FLAC3D on this issue, but you fail in the other issue (https://github.com/MoiseRousseau/Variational-Tet-Mesh/issues/1). What is different between both issues ? Can you send your GemPy input file ?

**Comment by nearfuture625** [comment]
@MoiseRousseau :Thanks for your reply, last time I proposed that the f3grid file exported using the export_flac3D_input() function provided in gempy could not be displayed in flac3D, I have solved it, the zone part is added before B8, the zone sequence number is added after B8, and the node column has 9 columns after the sequence number, I adjusted the order of the node columns, new_column_order = [1, 2, 4, 5, 3, 8, 6, 7] to output an F3Grid file that can be displayed in FLAC. I'm going to attach my modified export_flac3D_input() function file, but the problem I'm facing now is that there is a lack of a way to export a mesh file containing faults to analyze the stresses near the faults using FLAC3D.
[1017p.csv](https://github.com/cgre-aachen/gempy/files/13194251/1017p.csv)
[1017o.csv](https://github.com/cgre-aachen/gempy/files/13194250/1017o.csv)
[input_flac.txt](https://github.com/cgre-aachen/gempy/files/13194258/input_flac.txt)
Looking forward to your insights on the method of tomographic derivation

**Comment by ottaviani2** [comment]
Thank both of you for the amazing opportunity to export file .f3grid from gempy. I need to update the code, there is an asterisk that prevents the creation of zones.

The line
`out.write('\n*ZONES')`
should be 
`out.write('\nZONES')`

I attach the updated file
[input_flac.txt](https://github.com/cgre-aachen/gempy/files/14638309/input_flac.txt)

**Comment by javoha** [comment]
Resolved? Please feel free to reopen if not. I am also not sure how much of this is a gempy issue. But definitely a useful discussion.
