### ISSUE TITLE
graphic card

### ISSUE THREAD

**Issue by Joaquinfnz** [gempy-project/gempy#838]
How can i use my graphic card in the compile code of gempy? i have an Nvidia 1650 super, thanks

**Comment by javoha** [comment]
Hello,
this should be resolved with the new version of gempy (v3). Setting up pytorch should enable you do use your gpu:

```
gp.compute_model(data,
            engine_config=gp.data.GemPyEngineConfig(
            backend=gp.data.AvailableBackends.PYTORCH,
            use_gpu=True,
            dtype="float64"
                ))
```

Please feel free to reopen the issue if you encounter problems with this.
