### ISSUE TITLE
AttributeError: 'Sections' object has no attribute 'calculate_line_coordinates_2points'

### ISSUE THREAD

**Issue by xeon-ye** [gempy-project/gempy#841]
envs\py310\lib\site-packages\gempy_viewer\modules\plot_2d\plot_2d_utils.py", line 60, in make_section_xylabels
    xy = sections.calculate_line_coordinates_2points(p1, p2, n)
AttributeError: 'Sections' object has no attribute 'calculate_line_coordinates_2points'

**Comment by javoha** [comment]
Sorry for not resolving this. Hopefully thi is now outdated adn resolved with gempy v3.
