### ISSUE TITLE
Gempy import fails

### ISSUE THREAD

**Issue by Wrobs38** [gempy-project/gempy#842]
**Describe the bug**
I have installed : 
$ conda install theano
$ pip install gempy

I also installed the following components of Microsoft Visual Basic which were preventing the install of some components of Theano (or gempy) : 
- Python development 
- Desktop development with C++

I added the following SYSTEM environment variables:
- VCToolsInstallDir
- VCINSTALLDIR as C:\Program Files\Microsoft Visual Studio\2022\Community\VC
- LIB (not sure path is entered properly) 
- INCLUDE (not sure path is entered properly)
- SSL_CERT_FILE
and several PATH variables: 
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE
C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\OpenSSL-Win64\bin;%PATH%

as well as USER environment variable: 
VSINSTALLDIR
VCVARSBAT as C:\Program Files\Microsoft Visual Studio\2022\Community

I created a new environment : 
$ conda create --gempy_env3 gempy python==3.7

In Jupyter Notebook, after activating the environment, I run: 
import gempy as gp 

I get this error message: 
Traceback (most recent call last):

  File ~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [1] in <cell line: 1>
    import gempy as gp

  File ~\Anaconda3\lib\site-packages\gempy\__init__.py:24 in <module>
    from .core.model import Project, ImplicitCoKriging

  File ~\Anaconda3\lib\site-packages\gempy\core\model.py:1575
    match type(field_at_surface_points):
          ^
SyntaxError: invalid syntax

Not sure what the issue is and how to solve it. 
could you please help me? 

thanks a lot
JC

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.
2.
3.
...

**Expected behavior**
when i import gempy as gp
i'd expect it to load the gempy librairies

**Screenshots**

**Desktop (please complete the following information):**
  * OS: Windows 10
  * GemPy Version: 
  * can't get the version, i get an error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gempy'

it was installed from pip today, 29/11/2023

    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable): 7.0.6

**Additional context**

thank you very much for your help, looking forward to hear back from you 

regards
JC

**Comment by Wrobs38** [comment]
thanks @Japhiolite (sorry it took me a long while to get back to you). 
I tried but it did not work either.
Is it worth testing  the Version 3 instead? Florian mentioned that most dependencies are removed to ease the installation

thanks
JCW

**Comment by Varun019140** [comment]
> Hi and sorry for the late reply. Gempy v3 is available now and should hopefully solve these problems as you mentioned. Please feel free to reopen the issue if you keep encountering problems.

hi can you plzz tell me the steps from the starting ..how to install gempy
