### ISSUE TITLE
about compile_th_fn_geo()

### ISSUE THREAD

**Issue by huaijin321** [gempy-project/gempy#848]
I am a new user of this software，My GemPy version is V2.3.1，I got an error at the interp.compile_th_fn_geo() function when I ran "gempy-2.3.1\examples\tutorials\ch1_fundamentals\ch1_2a_data_manipulation.py" file。
My operating system is WINDOUWS 11.Here is my conda environment,my python version is 3.10.0.
Name	Version	Build
aesara	2.9.3	pypi_0
anyio	3.5.0	py310haa95532_0
argon2-cffi	21.3.0	pyhd3eb1b0_0
argon2-cffi-bindings	21.2.0	py310h2bbff1b_0
arrow	1.3.0	pypi_0
arviz	0.16.1	pypi_0
asttokens	2.4.1	pypi_0
async-lru	2.0.4	py310haa95532_0
attrs	23.1.0	py310haa95532_0
babel	2.11.0	py310haa95532_0
backcall	0.2.0	pyhd3eb1b0_0
beautifulsoup4	4.12.2	py310haa95532_0
blas	1	mkl
bleach	4.1.0	pyhd3eb1b0_0
blosc	1.21.3	h6c2663c_0
boost-cpp	1.82.0	h59b6b97_2
brotli-python	1.0.9	py310hd77b12b_7
bzip2	1.0.8	he774522_0
ca-certificates	2023.08.22	haa95532_0
cachetools	5.3.2	pypi_0
cairo	1.16.0	haedb8bc_5
certifi	2023.11.17	py310haa95532_0
cffi	1.16.0	py310h2bbff1b_0
cfitsio	3.47	h2bbff1b_7
charset-normalizer	3.3.2	pypi_0
click	8.1.7	pypi_0
cloudpickle	3.0.0	pypi_0
colorama	0.4.6	py310haa95532_0
comm	0.1.2	py310haa95532_0
cons	0.4.6	pypi_0
contourpy	1.2.0	pypi_0
cryptography	41.0.3	py310h3438e0d_0
cycler	0.12.1	pypi_0
debugpy	1.6.7	py310hd77b12b_0
decorator	5.1.1	pyhd3eb1b0_0
defusedxml	0.7.1	pyhd3eb1b0_0
etuples	0.3.9	pypi_0
exceptiongroup	1.2.0	pypi_0
executing	2.0.1	pypi_0
expat	2.5.0	hd77b12b_0
fastprogress	1.0.3	pypi_0
fftw	3.3.9	h2bbff1b_1
filelock	3.13.1	pypi_0
fontconfig	2.14.1	h9c4af85_2
fonttools	4.45.1	pypi_0
fqdn	1.5.1	pypi_0
freetype	2.12.1	ha860e81_0
freexl	1.0.6	h2bbff1b_0
gdal	3.6.2	py310h3565590_3
gempy	2.3.1	pypi_0
geos	3.8.0	h33f27b4_0
geotiff	1.7.0	h4545760_1
glib	2.69.1	h5dc1a3c_2
h5netcdf	1.3.0	pypi_0
h5py	3.10.0	pypi_0
hdf4	4.2.13	h712560f_2
hdf5	1.12.1	h51c971a_3
icc_rt	2022.1.0	h6049295_2
icu	73.1	h6c2663c_0
idna	3.6	pypi_0
imageio	2.33.0	pypi_0
iniconfig	2.0.0	pypi_0
intel-openmp	2021.4.0	haa95532_3556
ipykernel	6.25.0	py310h9909e9c_0
ipython	8.18.1	pypi_0
ipywidgets	8.0.4	py310haa95532_0
isoduration	20.11.0	pypi_0
jedi	0.19.1	pypi_0
jinja2	3.1.2	py310haa95532_0
joblib	1.3.2	pypi_0
jpeg	9e	h2bbff1b_1
json5	0.9.6	pyhd3eb1b0_0
jsonpointer	2.4	pypi_0
jsonschema	4.19.2	py310haa95532_0
jsonschema-specifications	2023.7.1	py310haa95532_0
jupyter	1.0.0	py310haa95532_8
jupyter-conda	3.4.1	pypi_0
jupyter-lsp	2.2.0	py310haa95532_0
jupyter_client	8.6.0	py310haa95532_0
jupyter_console	6.6.3	py310haa95532_0
jupyter_core	5.5.0	py310haa95532_0
jupyter_events	0.8.0	py310haa95532_0
jupyter_server	2.10.0	py310haa95532_0
jupyter_server_terminals	0.4.4	py310haa95532_1
jupyterlab	4.0.8	py310haa95532_0
jupyterlab_pygments	0.1.2	py_0
jupyterlab_server	2.25.1	py310haa95532_0
jupyterlab_widgets	3.0.9	py310haa95532_0
kealib	1.5.0	hde4a422_1
kiwisolver	1.4.5	pypi_0
krb5	1.20.1	h5b6d351_1
lazy-loader	0.3	pypi_0
lcms2	2.12	h83e58a3_0
lerc	3	hd77b12b_0
libboost	1.82.0	h3399ecb_2
libclang	14.0.6	default_hb5a9fac_1
libclang13	14.0.6	default_h8e68704_1
libcurl	8.4.0	h86230a5_0
libdeflate	1.17	h2bbff1b_1
libffi	3.4.4	hd77b12b_0
libgdal	3.6.2	hd879e17_3
libgpuarray	0.7.6	h2bbff1b_1
libiconv	1.16	h2bbff1b_2
libkml	1.3.0	h63940dd_7
libnetcdf	4.8.1	h6685c40_4
libpng	1.6.39	h8cc25b3_0
libpq	12.15	hb652d5d_1
libpython	2.1	py310haa95532_0
libsodium	1.0.18	h62dcd97_0
libspatialite	4.3.0a	h6ec8781_23
libssh2	1.10.0	hcd4344a_2
libtiff	4.5.1	hd77b12b_0
libwebp-base	1.3.2	h2bbff1b_0
libxml2	2.10.4	h0ad7f3c_1
libzip	1.8.0	h49b8836_0
logical-unification	0.4.6	pypi_0
lz4-c	1.9.4	h2bbff1b_0
m2w64-binutils	2.25.1	5
m2w64-bzip2	1.0.6	6
m2w64-crt-git	5.0.0.4636.2595836	2
m2w64-gcc	5.3.0	6
m2w64-gcc-ada	5.3.0	6
m2w64-gcc-fortran	5.3.0	6
m2w64-gcc-libgfortran	5.3.0	6
m2w64-gcc-libs	5.3.0	7
m2w64-gcc-libs-core	5.3.0	7
m2w64-gcc-objc	5.3.0	6
m2w64-gmp	6.1.0	2
m2w64-headers-git	5.0.0.4636.c0ad18a	2
m2w64-isl	0.16.1	2
m2w64-libiconv	1.14	6
m2w64-libmangle-git	5.0.0.4509.2e5a9a2	2
m2w64-libwinpthread-git	5.0.0.4634.697f757	2
m2w64-make	4.1.2351.a80a8b8	2
m2w64-mpc	1.0.3	3
m2w64-mpfr	3.1.4	4
m2w64-pkg-config	0.29.1	2
m2w64-toolchain	5.3.0	7
m2w64-tools-git	5.0.0.4592.90b8472	2
m2w64-windows-default-manifest	6.4	3
m2w64-winpthreads-git	5.0.0.4634.697f757	2
m2w64-zlib	1.2.8	10
mako	1.2.3	py310haa95532_0
markupsafe	2.1.1	py310h2bbff1b_0
matplotlib	3.8.2	pypi_0
matplotlib-inline	0.1.6	py310haa95532_0
minikanren	1.0.3	pypi_0
mistune	2.0.4	py310haa95532_0
mkl	2021.4.0	haa95532_640
mkl-service	2.4.0	py310h2bbff1b_0
mkl_fft	1.3.1	py310ha0764ea_0
mkl_random	1.2.2	py310h4ed8f06_0
msys2-conda-epoch	20160418	1
multipledispatch	1.0.0	pypi_0
nb_conda_kernels	2.3.1	py310haa95532_0
nbclient	0.8.0	py310haa95532_0
nbconvert	7.10.0	py310haa95532_0
nbformat	5.9.2	py310haa95532_0
nest-asyncio	1.5.6	py310haa95532_0
networkx	3.2.1	pypi_0
notebook	7.0.6	py310haa95532_0
notebook-shim	0.2.3	py310haa95532_0
numpy	1.22.3	py310h6d2d95c_0
numpy-base	1.22.3	py310h206c741_0
openjpeg	2.4.0	h4fc8c34_0
openssl	1.1.1w	h2bbff1b_0
overrides	7.4.0	py310haa95532_0
packaging	23.2	pypi_0
pandas	2.0.1	pypi_0
pandocfilters	1.5.0	pyhd3eb1b0_0
parso	0.8.3	pyhd3eb1b0_0
pcre	8.45	hd77b12b_0
pcre2	10.42	h0ff8eda_0
pickleshare	0.7.5	pyhd3eb1b0_1003
pillow	10.1.0	pypi_0
pip	23.3.1	py310haa95532_0
pixman	0.40.0	h2bbff1b_1
platformdirs	4.0.0	pypi_0
pluggy	1.3.0	pypi_0
ply	3.11	py310haa95532_0
pooch	1.8.0	pypi_0
poppler	22.12.0	h0bf3bde_3
poppler-data	0.4.11	haa95532_1
proj	6.2.1	h3758d61_0
prometheus_client	0.14.1	py310haa95532_0
prompt-toolkit	3.0.41	pypi_0
prompt_toolkit	3.0.36	hd3eb1b0_0
psutil	5.9.0	py310h2bbff1b_0
pure_eval	0.2.2	pyhd3eb1b0_0
pycparser	2.21	pyhd3eb1b0_0
pyevtk	1.6.0	pypi_0
pygments	2.17.2	pypi_0
pygpu	0.7.6	py310h9128911_0
pymc	5.10.0	pypi_0
pyopenssl	23.2.0	py310haa95532_0
pyparsing	3.1.1	pypi_0
pyqt	5.15.10	py310hd77b12b_0
pyqt5	5.15.9	pypi_0
pyqt5-plugins	5.15.9.2.3	pypi_0
pyqt5-qt5	5.15.2	pypi_0
pyqt5-sip	12.13.0	py310h2bbff1b_0
pyqt5-tools	5.15.9.3.3	pypi_0
pysocks	1.7.1	py310haa95532_0
pytensor	2.18.1	pypi_0
pytest	7.4.3	pypi_0
python	3.10.0	h96c0403_3
python-dateutil	2.8.2	pyhd3eb1b0_0
python-dotenv	1.0.0	pypi_0
python-fastjsonschema	2.16.2	py310haa95532_0
python-json-logger	2.0.7	py310haa95532_0
pytz	2023.3.post1	py310haa95532_0
pyvista	0.39.1	pypi_0
pyvistaqt	0.10.0	pypi_0
pywin32	305	py310h2bbff1b_0
pywinpty	2.0.10	py310h5da7b33_0
pyyaml	6.0.1	py310h2bbff1b_0
pyzmq	25.1.0	py310hd77b12b_0
qhull	2020.2	h59b6b97_2
qt-main	5.15.2	he2df7e6_10
qt5-applications	5.15.2.2.3	pypi_0
qt5-tools	5.15.2.1.3	pypi_0
qtconsole	5.5.0	py310haa95532_0
qtpy	2.4.1	py310haa95532_0
referencing	0.30.2	py310haa95532_0
requests	2.31.0	py310haa95532_0
rfc3339-validator	0.1.4	py310haa95532_0
rfc3986-validator	0.1.1	py310haa95532_0
rpds-py	0.10.6	py310h062c2fa_0
scikit-image	0.22.0	pypi_0
scikit-learn	1.3.2	pypi_0
scipy	1.11.4	pypi_0
scooby	0.9.2	pypi_0
seaborn	0.13.0	pypi_0
send2trash	1.8.2	py310haa95532_0
setuptools	68.0.0	py310haa95532_0
sip	6.7.12	py310hd77b12b_0
six	1.16.0	pyhd3eb1b0_1
sniffio	1.2.0	py310haa95532_1
soupsieve	2.5	py310haa95532_0
sqlite	3.41.2	h2bbff1b_0
stack-data	0.6.3	pypi_0
stack_data	0.2.0	pyhd3eb1b0_0
terminado	0.17.1	py310haa95532_0
theano	1.0.5	py310haa95532_0
threadpoolctl	3.2.0	pypi_0
tifffile	2023.9.26	pypi_0
tiledb	2.3.3	h3649cd2_2
tinycss2	1.2.1	py310haa95532_0
tk	8.6.12	h2bbff1b_0
tomli	2.0.1	py310haa95532_0
toolz	0.12.0	pypi_0
tornado	6.3.3	py310h2bbff1b_0
traitlets	5.14.0	pypi_0
types-python-dateutil	2.8.19.14	pypi_0
typing-extensions	4.8.0	pypi_0
typing_extensions	4.7.1	py310haa95532_0
tzdata	2023.3	pypi_0
uri-template	1.3.0	pypi_0
uriparser	0.9.7	h2bbff1b_0
urllib3	2.1.0	pypi_0
vc	14.2	h21ff451_1
vs2015_runtime	14.27.29016	h5e58377_2
vtk	9.3.0	pypi_0
wcwidth	0.2.12	pypi_0
webcolors	1.13	pypi_0
webencodings	0.5.1	py310haa95532_1
websocket-client	0.58.0	py310haa95532_4
wheel	0.41.2	py310haa95532_0
widgetsnbextension	4.0.5	py310haa95532_0
win_inet_pton	1.1.0	py310haa95532_0
winpty	0.4.3	4
xarray	2023.11.0	pypi_0
xarray-einstats	0.6.0	pypi_0
xerces-c	3.2.4	hd77b12b_1
xz	5.4.2	h8cc25b3_0
yaml	0.2.5	he774522_0
zeromq	4.3.4	hd77b12b_0
zlib	1.2.13	h8cc25b3_0
zstd	1.5.5	hd43e919_0
![屏幕截图 2023-12-06 193230](https://github.com/cgre-aachen/gempy/assets/83524134/0676466a-d80d-4099-b49b-86ffc64dc108)

**Comment by huaijin321** [comment]
My aesara version is 2.9.3

**Comment by javoha** [comment]
Hi,
sorry for not replying faster: We were busy working on gempy v3 moving away from theano and aesara (due to issues like yours). The legacy version of gempy can be found[ here](https://github.com/gempy-project/gempy_legacy) now. If you are still interested, I would recommend installing the new version though, as it should resolve these issues.

I will close this issue now but please feel free to reopen or open a new issue if you encounter any problems with the new version.
