### ISSUE TITLE
About issues encountered when using pyinstaller to package Windows programs

### ISSUE THREAD

**Issue by Lian-Po-s-Study-Diary** [gempy-project/gempy#862]
I use pyinstaller to package Python scripts into Windows programs. An error occurred after the program was run, which should be related to the gcc compiler. It should be possible to run the script in a normal Python environment with Theano installed, but an error will be reported after packaging it into a Windows program. May I ask how I can solve this problem?

**Comment by Lian-Po-s-Study-Diary** [comment]
![QQ截图20240103223234](https://github.com/cgre-aachen/gempy/assets/154105481/5281c6b5-08dd-4c6a-ba32-8dca3e3f47b9)

**Comment by Lian-Po-s-Study-Diary** [comment]
After deleting some environment variables, the problem has been resolved.But after running the exe file, the calculation time of the model is greatly extended. Is there any solution.

**Comment by Lian-Po-s-Study-Diary** [comment]
I found that this seems to be caused by "m2w64 toolchain" or "g++". I tried to copy "g++. exe" to the directory, but a new error message appeared and the model could not be generated

**Comment by javoha** [comment]
Hi,
sorry for the very late reply, I think we were note sure how to solve this and additionally working on the new gempy version. Have you tried this uisng gempy v3 (which does not rely on Theano anymore). Would be great to hear if this is resolved.

**Comment by Lian-Po-s-Study-Diary** [comment]
thank you，this is resolved by using gempy v3
