### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by dmartinezdi** [gempy-project/gempy#872]
**Describe the bug**
I have two main issues, the first one is that if I follow the installation guide when I am trying to install gempy it is not possible to recognize Microsoft Visual C++ 14.0 or greater, this happens when I create the environment with python 3.7.0 as suggested. But, when I change to a higher version of python such as 3.8 or 3.9 I am able to install theano and gempy without any problem but when I proceed to use it as importing the package I got the error showed in the screenshot below, something of syntaxis in the core code of gempy. 

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.I followed the installation guide on the webpage

**Expected behavior**
Installed and import gempy functionally

**Screenshots**
1. When I use python 3.7: 
![image](https://github.com/cgre-aachen/gempy/assets/84647722/0234acc8-b657-4c58-9d16-613afd453beb)
2. When I use python >=3.8:
![image](https://github.com/cgre-aachen/gempy/assets/84647722/91cc4e61-b436-4139-b908-9eedb8ea71c8)

**Desktop (please complete the following information):**
  * OS: Windows 11
  * GemPy Version
    * Installed via pip: provide GemPy version (e.g. 2.0.1)

** Extra information** 
In the first case I have already installed the Microsoft visual c++.
In the second I can install gempy but it does not work.

**Comment by Leguark** [comment]
GemPy is only working on Python 3.10 or older since a bit no
