### ISSUE TITLE
Error with geo_model.add_surface_values

### ISSUE THREAD

**Issue by Anagabrielamantilla** [gempy-project/gempy#876]
Hi, I am trying to add properties to each surface of my model named 'geo_model' : 

`geo_model.add_surface_values([3800, 4000, 2500, 3500, 5500], ['vp'])  #m/s vp`

but I am getting this error: AttributeError: 'GeoModel' object has no attribute 'add_surface_values'

Does the function name change with new gempy version? I just updated to gempy 2024.

**Comment by Leguark** [comment]
Hi @Anagabrielamantilla, the new API has changed a bit. Now for simplicity only the `gempy` function works, i.e. `gempy.add_surface_values`. You can see an example of this implementation in the following example https://docs.gempy.org/tutorials/a_getting_started/get_started.html#surfaces

Remember that you can keep using gempy v2 with pip install gempy_legacy
