### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by Toroitich6783** [gempy-project/gempy#878]
**What is your question?**
I had an issue with the installation of Gempy on windows, Which python and Gempy version are recommended or would you provide me with some guidelines.

**Comment by javoha** [comment]
Hello,
did you have an issues following the installation guide for the most recent version? I remember an issue with Python 3.11 so maybe start with Python 3.10 if possible,

**Comment by javoha** [comment]
@Toroitich6783 : I will close this for now as it is hopefully resolved. Please feel free to reopen the issue if problems persist.
