### ISSUE TITLE
AttributeError                            Traceback (most recent call last) Cell In[2], line 1 ----> 1 geo_model = gp.create_model('Model1')       2 geo_model = gp.init_data(geo_model, extent=[0, 791, 0, 200, -582, 0], resolution=[100, 10, 100])  AttributeError: module 'gempy' has no attribute 'create_model'.........

### ISSUE THREAD

**Issue by Varun019140** [gempy-project/gempy#885]
**Describe the bug**
A clear and concise description of what the bug is. Include error messages / 
tracebacks. If useful include screenshots.

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.
2.
3.
...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
  * OS: (e.g. iOS)
  * GemPy Version
    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable)

**Additional context**

**Comment by javoha** [comment]
See #881
