### ISSUE TITLE
facing error

### ISSUE THREAD

**Issue by Varun019140** [gempy-project/gempy#886]
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 img = mpimg.imread('wells.png')
      2 p2d = gpv.plot_2d(geo_model, show=False)
      3 p2d.axes[0].imshow(img, origin='upper', alpha=.8, extent=(0, 791, -582, 0))

File ~\anaconda3\lib\site-packages\matplotlib\image.py:1561, in imread(fname, format)
   1554 if isinstance(fname, str) and len(parse.urlparse(fname).scheme) > 1:
   1555     # Pillow doesn't handle URLs directly.
   1556     raise ValueError(
   1557         "Please open the URL for reading and pass the "
   1558         "result to Pillow, e.g. with "
   1559         "``np.array(PIL.Image.open(urllib.request.urlopen(url)))``."
   1560         )
-> 1561 with img_open(fname) as image:
   1562     return (_pil_png_to_float_array(image)
   1563             if isinstance(image, PIL.PngImagePlugin.PngImageFile) else
   1564             pil_to_array(image))

File ~\anaconda3\lib\site-packages\PIL\ImageFile.py:105, in ImageFile.__init__(self, fp, filename)
    101 self.decodermaxblock = MAXBLOCK
    103 if is_path(fp):
    104     # filename
--> 105     self.fp = open(fp, "rb")
    106     self.filename = fp
    107     self._exclusive_fp = True

FileNotFoundError: [Errno 2] No such file or directory: 'wells.png'

**Comment by SpongeGirl** [comment]
I think this is what you need.
![image](https://github.com/gempy-project/gempy/assets/44236813/866cbad6-6442-4036-a181-94426295c18f)

**Comment by javoha** [comment]
See #881
