### ISSUE TITLE
AttributeError: module 'gempy' has no attribute 'create_model'

### ISSUE THREAD

**Issue by nqqcuong** [gempy-project/gempy#892]
**What is your question?**
I try to running examples but then I got error
AttributeError: module 'gempy' has no attribute 'create_model'

Conda
Jupyter Notebook 7.0.8
Python 3.11.9

**Comment by javoha** [comment]
Hi,
can you specify which examples you were trying to run. And are you working with the most recent version of gempy (v3)?

If you take a look at the current documentation, `create_model` does not exist anymore in v3. I recommend runnig a small example like [this ](https://docs.gempy.org/examples/geometries/a01_horizontal_stratigraphic.html#sphx-glr-examples-geometries-a01-horizontal-stratigraphic-py) to see if the new version is running and to get used to the API changes.

Cheers
Jan

**Comment by javoha** [comment]
Hopefully resolved with comment above. Please feel free to reopen if the issue persists.
