### ISSUE TITLE
Gempy model export to numpy

### ISSUE THREAD

**Issue by WATCH0620** [gempy-project/gempy#893]
Hello, I would like to ask how to export the model generated by gempy to numpy.ndarray?

**Comment by javoha** [comment]
Hi,
you can access the different ndarrays of the solution using:
`geo_data.solutions.raw_arrays`

I guess the most important results would be the vertices of the grid and the corresponding solutions:
```
geo_data.solutions.raw_arrays.lith_block
geo_data.solutions.raw_arrays.vertices
```
