### ISSUE TITLE
Legacy vs current GEMPY version

### ISSUE THREAD

**Issue by Al3xdevito** [gempy-project/gempy#897]
Hi, 

I have been trying to add a velocity model to the geological model, as the Transform2021 tutorial (https://github.com/devitocodes/transform2021/blob/main/creating_synthetics.ipynb). Looks like the current version of GEMPY does not support this functions, for example:
AttributeError                            Traceback (most recent call last)
Cell In[26], line 1
----> 1 geo_model.add_surface_values([1.5,1.5, 1.75, 2.5,4.5], ['vp'])
AttributeError: 'GeoModel' object has no attribute 'add_surface_values'

My question is: Should I try the Gempy legacy first or try to debug the current gempy version.

**Comment by javoha** [comment]
Hi,
good question - I am not 100% sure but I was also not able to find the exact equivalent for this in gempy v3. Let me check again and come back to you. For now: You can access the results and set a numpy array with the shape of the `geo_model.solutions.raw_arrays.lith_block` and assign values based on this lith block. You can basically use the same logic used in the notebook you provided afterwards. I tried this quickly just using the lith block for another model:

```
shape=[50, 20, 20] # corresponding to resolution of gempy model

# Reshaping our data to the shape required by Devito
reshaped = np.reshape(data.solutions.raw_arrays.lith_block, shape, order='C')
reshaped.shape

import matplotlib.pyplot as plt

# Take the center slice in the y direction in this case
# Remember that in Devito, indexing convention is [x, y, z] (need to flip for correct imshow display)
plt.imshow(reshaped[:,5,:].T, cmap='viridis', origin='lower')
plt.colorbar()
plt.show()```

This gave me something like this (sorry for low res), you would still need to create the array with your physical properties based on the lith block array.

![issue](https://github.com/gempy-project/gempy/assets/38279459/e6ae3ba2-ff5d-4e83-a70f-da388c0d3d56)

Does this work for your case? Of course we would like you to work with gempy v3.

Cheers
Jan

**Comment by javoha** [comment]
Hi @Al3xdevito,
I will close this issue for now, please feel free to reopen if you need further assistance.
