### ISSUE TITLE
After the model is exported to pyvista, the coordinates are incorrect

### ISSUE THREAD

**Issue by Lian-Po-s-Study-Diary** [gempy-project/gempy#898]
After I built the model using gempy3.0, I used the create_depth_maps_from_gempy method of gemgis to output the model to pyvista and found that the coordinates were wrong. It may be because gempy uses the method of normalizing coordinates. How should I restore the model to the actual size and actual position?  Or, is there a way to directly output model files in gempy3.0?

**Comment by javoha** [comment]
Hi,
so if understand you correctly the coordinates within gempy are correct, but using the gemgis function does not work? As far as I know gemgis has not been updated to work with gempy v3, so it might take a while until this functionality is available. 
I would suggest creating an issue in gemgis to ask about the current state.
Gempy v3 as of now does not have the functionality to save a full model. You can however export all the raw arrays of the result using `.solutions`.
Just some examples: `geo_model.solutions.dc_meshes` to retrieve the meshes plotted in vista, or `data.solutions.raw_arrays.vertices` and `data.solutions.raw_arrays.lith_block` for getting the vertices and lithologies of the grid.
Does this help?

**Comment by Lian-Po-s-Study-Diary** [comment]
Thank you for your help. I successfully restored the model using geo_model. transforme
