### ISSUE TITLE
Lith blocks rotated in comparison to meshes?

### ISSUE THREAD

**Issue by AlexanderJuestel** [gempy-project/gempy#908]
**Describe the bug**

When plotting a simple model, I noticed that the meshes are plotted correctly but that the lith blocks are flipped in the Y-axis  direction. See screenshot. I will have a look in the source code to see what is going on here :)

``gpv.plot_3d(geo_model, show_data=True, image=False, plotter_type='basic')``

![image](https://github.com/gempy-project/gempy/assets/45469915/7ef2a4b6-34c3-475f-93e2-c22ad5ed0d76)

**Expected behavior**
Lith blocks and meshes should have the same orientation.

**Comment by javoha** [comment]
Hey, 
interesting - I have not seen this behavior in my models. Can you share the code so I can take a look. Why exactly do you have downward facing orientations?

**Comment by AlexanderJuestel** [comment]
Good questions :D attached you will find the notebook and the data. You should be able to run it from cell 28 onwards.

Thanks for having a look :)

[Data.zip](https://github.com/user-attachments/files/15764567/Data.zip)

**Comment by javoha** [comment]
Ok, so the problem here is your extent. Your extent in x direction goes from high to low. If you just switch those values everything works fine. Not 100% sure where this blows up, but it somehow leads to a weird flip in the model.

**Comment by AlexanderJuestel** [comment]
That happens when you do copy and paste :D
