### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by KodalAnwesha** [gempy-project/gempy#912]
**What is your question?**
It's continuously showing attribute error whenever I try to create a model or plot in 2D. Is there any prerequisite of using GemPy?

**Comment by KodalAnwesha** [comment]
I am using Gempy-2024.1.0 in Python-3.11

**Comment by KodalAnwesha** [comment]
Yes, actually, I had installed it's current version- 2024.1.0 in Python-3.11, but while working with it, it is always showing attribute error. 
Like, if I am trying to create a model, I am using gp.create_model command, but it's showing module 'gempy' has no attribute 'create_model'. 

Gempy- 2024.2.0 isn't even getting imported in Python 3.11.

**Comment by javoha** [comment]
Hi,
we are aware of the importing issue regarding the 2024.2.0 release and are working on a solution. The 2024.1.0 version should work though. Are you actually using "create_model"? Because that does not exist anymore in gempy v3. There were some changes in the API and the function is now called "create_geomodel". You can take a look at the examples ([I like this one](https://docs.gempy.org/examples/geometries/g07_combination.html#sphx-glr-examples-geometries-g07-combination-py)) for a closer look.

**Comment by KodalAnwesha** [comment]
Okay, thanks! But the gempyviewer is also showing similar kind of error. Like if I run this code from GemPy tutorial:

img = mpimg.imread('wells.png')
p2d = gpv.plot_2d(geo_model, show=False)


the error is: it has no attribute input_transform. How to fix this?

**Comment by KodalAnwesha** [comment]
Could you please tell me which modules should be installed before working on GemPy? And which version of PYTHON will be compatible for GemPy v3?

**Comment by javoha** [comment]
Hey,
it seems like there are some issues also with the numpy 2.0.0 release. I was bale to reproduce your errors. For me having gempy on:
gempy                    2024.1.4  
gempy-engine        2024.1.4.2  
gempy-viewer         2024.1.4  
AND numpy on 1.26.4 did the trick. Sorry for the inconvenience, hopefully we get all the dependency issues fixed soon.

**Comment by KodalAnwesha** [comment]
Can we work with GemPy V2? Is it compatible with all versions?

**Comment by javoha** [comment]
Gempy v2 is available in the gempy legacy version, but I do believe you will have more dependency issues using that. This sometimes part of being an open source project. Did my suggestions solve the problem for you though?

**Comment by KodalAnwesha** [comment]
I tried to solve the issue using both Python-3.11 and 3.12, but this issue is not getting solved. I will again try the versions you recommended and will let you know. Because I have tried both Gempy version 2024.1.0 and 2024.2.0, but none of them are working.

**Comment by Leguark** [comment]
GemPy 2024.2 compatibility with numpy and scipy version 2 has been fixed.
