### ISSUE TITLE
Gempy  module  not Found

### ISSUE THREAD

**Issue by kawaalina** [gempy-project/gempy#919]
Hello, I downloaded Gempy using the Anaconda terminal and typed the following command.

import gempy

He gave the following

ModuleNotFoundError: No module named 'gempy'

Although the download process was successful and all packages were downloaded using "pip", I tried it on Jupyter and it did not work either! What is the reason for this? i use wendows Windows System.

**Comment by javoha** [comment]
Hi,
so I assume you folled the installation guide and used `pip install gempy`? And when trying to run it in the same environment it wasnt able to find gempy? can you check the installation using `conda list` in your environment?
Cheers
Jan

**Comment by kawaalina** [comment]
yes,  it's on conda list!
gempy                     2.3.2                    pypi_0    pypi

**Comment by kawaalina** [comment]
it's work! Thanx so much <3

**Comment by javoha** [comment]
Great, have fun geomodeling!
