### ISSUE TITLE
add_orientations function does not work with orientation argument

### ISSUE THREAD

**Issue by benk-mira** [gempy-project/gempy#921]
**Describe the bug**
The orientation argument to add_orientations is a Sequence[np.ndarray] in the docstrings.  Passing a list of arrays as the docstring implies fails at line 130 of manipulate_points.py since slicing is not supported for lists.  Ignoring the doctrings and passing an array instead fails at line 128 of the same file because arrays are not truthy in that way.

**To Reproduce**
```
        extent = [-1000, 1000, -1000, 1000, -500, 500]
        geo_model = gp.create_geomodel(
            project_name="test",
            extent=extent,
            refinement=4,
            structural_frame=gp.data.StructuralFrame.initialize_default_structure()
        )
        gp.add_orientations(geo_model, x=[0], y=[0], z=[0], elements_names=['surface1'], orientation=[[0, 0, 0]])
```
![image](https://github.com/user-attachments/assets/f9b17e7d-64b5-4692-87ae-5ce0740220ef)

```
        extent = [-1000, 1000, -1000, 1000, -500, 500]
        geo_model = gp.create_geomodel(
            project_name="test",
            extent=extent,
            refinement=4,
            structural_frame=gp.data.StructuralFrame.initialize_default_structure()
        )
        gp.add_orientations(geo_model, x=[0], y=[0], z=[0], elements_names=['surface1'], orientation=np.array([0, 0, 0]))
```
![image](https://github.com/user-attachments/assets/2b4bde32-f6b8-4814-a8c5-a3c2173c0193)

**Comment by javoha** [comment]
Hi,
sorry for not replying for a while and thanks for the catch. I made a pull request to fix this, hopefully it will be resolved soon.

**Comment by agzimmerman** [comment]
> Hi, sorry for not replying for a while and thanks for the catch. I made a pull request to fix this, hopefully it will be resolved soon.

i.e. #929

**Comment by javoha** [comment]
This should now be fixed in main. The pip release will follow in the future.

**Comment by benk-mira** [comment]
Thank you for addressing this! I'll test the fix on main.
