### ISSUE TITLE
Export possibilities of a gempy modell:

### ISSUE THREAD

**Issue by Sebadita** [gempy-project/gempy#928]
Hi everyone! 

I have created some surface and i would like to export them but not as a xyz file, but as other format where the color of each layer can be saved, like .dxf. 

Is that possible?

Thank u in advance! 

VG

Sebadita

**Comment by javoha** [comment]
Hi,
there is no function at the moment to directly export all of this in a specific format. You can however, similar to exporting the xyz data, access and save the colors and everything else.

`geo_model.structural_frame.elements_colors`

If you ever feel like writing a convenience function specifically to export certain formats, we are happy to get your pull request and add it to the gempy addons package.

Cheers,
jan

**Comment by javoha** [comment]
Hope this is answered, feel free to reopen if you have additional questions.
