### ISSUE TITLE
ColorsGenerator never returns random colors

### ISSUE THREAD

**Issue by artygo8** [gempy-project/gempy#930]
**Describe the bug**

ColorsGenerator never actually returns random colors.

```
Traceback (most recent call last):
  File "/home/arthurgossuin/code/gempy/z.py", line 6, in <module>
    next(color_iterator)
  File "/home/arthurgossuin/code/gempy/gempy/core/color_generator.py", line 69, in __next__
    result = self.hex_colors[self._index]
             ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range
```

**To Reproduce**

Here is the content of the file used to produce the bug:

```
import gempy as gp

color_iterator = gp.ColorsGenerator()

for color in range(len(color_iterator.hex_colors) + 1):
    next(color_iterator)
```

**Expected behavior**

The [code](https://github.com/gempy-project/gempy/blob/main/gempy/core/color_generator.py#L66-L74) seems to imply that we should fall back on random colors once there are no colors left in `hex_colors`.

**Screenshots**

pass

**Desktop (please complete the following information):**
  * OS: irrelevant
  * GemPy Version
    * 3bf56a9

**Additional context**

As an ex geology student, and now fulltime software developer, I was intrigued by the library and started browsing the files when I found that bug. I would be happy to contribute further if you are open to it.

**Comment by agzimmerman** [comment]
[artygo8](https://github.com/artygo8), thanks for your contribution.

I am skeptical of how you modified `up_next` to append the `hex_colors` list.

I wasn't familiar yet with this part of the code, but after a brief read of the original and of your changes, it is not clear to me that the iterator should be modifying the list (by appending random colors).

This may be a case where we should consider "Explicit is better than implicit" from the [Zen of Python](https://peps.python.org/pep-0020/). 

Have you determined where this behavior would be useful? If so, then maybe there is a more explicit way to handle it. At the very least we can explain with a comment.

I only reviewed very briefly so far, so forgive me if I missed something obvious.
