### ISSUE TITLE
3d voxel representation

### ISSUE THREAD

**Issue by Sebadita** [gempy-project/gempy#935]
Hi everyone!

Is it possible to visualize the 3d voxel of the geo_model, just like a block model?

thank u in advance!

**Comment by javoha** [comment]
Hi,
do you have some context what you want to achieve exactly. This is not implemented in gempy but it should be rather straightforward to do in pyvista. Something like this works:

```
arr = geo_model.solutions.raw_arrays.lith_block.reshape(geo_model.grid.regular_grid.resolution)

vol = pv.ImageData()
vol.dimensions = arr.shape
vol["array"] = arr.ravel(order="F")

vol.plot()
```
Is that what you need?

**Comment by javoha** [comment]
I will mark this as answered, feel free to reopen if you have further questions.
