### ISSUE TITLE
Fault behavior documentation 

### ISSUE THREAD

**Issue by HighPerformance01** [gempy-project/gempy#94]
I think fault behavior is not documented very well. e.g. displacement,  throw, heave ....

**Comment by Leguark** [comment]
Yes, we agree. We are in the middle of a re design (you can take a sneak peek in the new structure branch) to make everything much more robust and modular.
But if you go through the pain of understand it, please feel free to contribute!

**Comment by HighPerformance01** [comment]
Thank you Leguark for your response. 

Would you please provide an estimate when this may be available. This will help me a lot to plan other tools development that could depend on Gempy.

**Comment by HighPerformance01** [comment]
Thank you Leguark for the update. I am working on some seismic inversion work and need to represent fault properties correctly in the model (throw, heave, ....). For building model, I am trying to start using Gempy. Gempy is a great choice and I think this would be much more famous in near future due to many factors one of which python popularity these days. Not to forget Gempy great functionality :)

**Comment by Leguark** [comment]
Great to hear! Right now we have in a bigger or lesser extent: infinite faults, faults network and rather simple finite faults. Hopefully in the following weeks we will have a decent documentation of them. 

But to get faults up to speed, we will need a PhD student centered on them. So if anybody has time and does not know what to do with it please contact me! :smile:
