### ISSUE TITLE
Define velocity property and export the property model

### ISSUE THREAD

**Issue by jcgeophysic** [gempy-project/gempy#942]
Hi! I hope you are doing well!
I'm new user of Gempy and I tried to follow videos and tutorials for building a velocity model to use it later in Devito. Many things have changed, so I already built a model but I can not assing the velocity value to each layer in the model. It seems that GeophysicsInput module just work for gravity models. At the end, I like to export the velocity model, however, the way that is explained in the transform 21 video, is not working.
I really appreciate your help.

Best regards

**Comment by javoha** [comment]
Hi,
thanks for the question. Maybe I can offer a basic solution.
When creating a gempy model we create a regular grid (at least as the default). The coordinates for this grid are stored in `geo_data.grid.regular_grid.values`. For each coordinate we have a corresponding lithology integer ID stored in `geo_data.solutions.raw_arrays.lith_block`.
If you want to set a single specific velocity per rock unit (structural element) you can create an array of the same size and replace each lithology ID with a velocity value. 
Going more advanced you could also populate the volumes per rock with unit interpolated fields (e.g. using RBF, Kriging) if you have measurements or with Random fields (e.g. using Sequential Gaussian Simulation) if you dont.
Does this help/answer your question?
Cheers
Jan

**Comment by jcgeophysic** [comment]
Hi Javoha, yes, it helped!
Thank you very much.

Regards,

Jhonny

**Comment by javoha** [comment]
That's good to hear, let me know if you need more help.
