### ISSUE TITLE
Attribute error in gp.compute_model(data)

### ISSUE THREAD

**Issue by KodalAnwesha** [gempy-project/gempy#946]
Hello,

While working on GemPy I faced an error like, 
AttributeError: type object 'InterpolationInput' has no attribute 'from_structural_frame'.

I was using the code gp.compute_model(data).

But this same code was running 3 months back while I was working on GemPy.
Is there any recent changes in GemPy?

Please let me know how to fix this. It's urgent!

Thank you!

**Comment by javoha** [comment]
Hi,
we have not encountered this issue, maybe try creating a fresh environment with all the latest versions and see if the problem persists? Otherwise we would need more specific details on your model to figure out a solution.
Cheers,
Jan

**Comment by KodalAnwesha** [comment]
It is fixed. Thank you for the suggestion!
