### ISSUE TITLE
Extend installation information

### ISSUE THREAD

**Issue by flohorovicic** [gempy-project/gempy#955]
**Is your feature request related to a problem? Please describe.**
Extend info for installation 

**Describe the solution you'd like**
More details on requirement to install also `gempy-viewer`, info about PyVista/ VTK, Pandas (when required, when not), PyTorch etc.

**Additional context**
Change in repo and update in Sphinx required for website [https://docs.gempy.org/tutorials/a_getting_started/get_started.html#sphx-glr-tutorials-a-getting-started-get-started-py](https://docs.gempy.org/tutorials/a_getting_started/get_started.html#sphx-glr-tutorials-a-getting-started-get-started-py)

**Comment by malflink** [comment]
Hi, Thanks very much for all the comments. I am going to look again today. Mike

**Comment by flohorovicic** [comment]
Also required: update of main documentation page (still contains reference to old probability module).

**Comment by grantboxer** [comment]
I am trying to run GemPy but I am getting erros relating to python issues. I have tried doing a clean install into a new environment but then I get problems with python versions.
It would be really helpful for new users to have the python version and how to set-up a python environment suitable for running GemPy.

**Comment by javoha** [comment]
Hi @grantboxer,
thnaks for your question. Could you specify the exact problems. A fresh environment using Python 3.12.xx and `pip install gempy` does not work for you?

**Comment by grantboxer** [comment]
Good morning,

I have created a new environment for gempy and have 3.12 installed. When I run "pip install gempy", I get the following.

Is this a fatal error? Seems like an error in loading the Theano package.

--------------------------------------------------------------------------------------

(gempy) C:\Users\boxer>pip install gempy
Requirement already satisfied: gempy in c:\users\boxer\gempy (2.2.12)
Collecting pandas==1.3.4 (from gempy)
  Downloading pandas-1.3.4.tar.gz (4.7 MB)
     ---------------------------------------- 4.7/4.7 MB 5.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Theano>=1.0.4 (from gempy)
  Downloading Theano-1.0.5.tar.gz (2.8 MB)
     ---------------------------------------- 2.8/2.8 MB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      C:\Users\boxer\AppData\Local\Temp\pip-install-5mgbgebe\theano_e3b2886f4fc245059fec62852eb9d3a6\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\Users\boxer\gempy\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\boxer\gempy\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\boxer\gempy\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\boxer\AppData\Local\Temp\pip-build-env-hdjk_uhb\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\boxer\AppData\Local\Temp\pip-build-env-hdjk_uhb\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\boxer\AppData\Local\Temp\pip-build-env-hdjk_uhb\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\boxer\AppData\Local\Temp\pip-build-env-hdjk_uhb\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 74, in <module>
        File "C:\Users\boxer\AppData\Local\Temp\pip-install-5mgbgebe\theano_e3b2886f4fc245059fec62852eb9d3a6\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\boxer\AppData\Local\Temp\pip-install-5mgbgebe\theano_e3b2886f4fc245059fec62852eb9d3a6\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by flohorovicic** [comment]
Hi @grantboxer,

Yes, this looks like a theano installation issue. But since theano is actually not anymore used by the newest version of GemPy (mainly due to the continuing installation issues...), it seems that your pip is outdated.

Please try first to update pip with:

```pip install --upgrade pip```

or

```python -m pip install --upgrade pip```

More inför for example here: https://www.wikihow.com/Update-Pip#:~:text=Run%20the%20command%20python%20%2Dm,pip%20install%20%2D%2Dupgrade%20pip%20.

Then, try with a clean environment and re-install GemPy with pip:

```pip install gempy[base]```

For more information options (especially the viewer, if you want to visualise models in 3-D), see also:

https://docs.gempy.org/installation.html

**Comment by grantboxer** [comment]
Hi Florien, this is a common problem with novice users trying to use python for scientific applications. I have tried a number of python programs in the past and every time I get issues where the software just doesn't run. I do not know if there is a better way to describe the environments required for software to run. For someone trying to use the software without a deep knowledge of python it is very frustrating.
Anyway, thanks for the advice and I will persevere! 
Cheers Grant

**Comment by flohorovicic** [comment]
Hi Grant,

Yes, I agree - a bit of a hurdle at the beginning, with the different types of environments and Python distributions. We usually give our students two options, when they start learning to use scientific applications in Python:
- Start with complete online environments, for example Google Colab (in which GemPy runs, see for example: https://colab.research.google.com/drive/1JhXMJrGrJeXJK2MOB-btrEb_eyA8hk3o?usp=sharing - this works in general, but comes with some limitations, of course. But good for a start when you don't want to care about local installations, environments, etc.
- Use a Python distribution, such as Anaconda, with a local installation. This helps with a lot of common installation issues, but still requires some knowledge. A lot of help is available online, but it requires a bit to get used to it.

Anyway, once you make it through the first learning steps, a whole world of possibilities opens-up with scientific programming. So, hopefully, worth it!

**Comment by flohorovicic** [comment]
P.S.: I'll close this issue as it related to a documentation update, which is now implemented. If you have more questions or issues, feel free to open a new issue or, for general questions, a discussion item on: https://github.com/orgs/gempy-project/discussions

**Comment by flohorovicic** [comment]
P.S.: I'll close this issue as it related to a documentation update, which is now implemented. If you have more questions or issues, feel free to open a new issue or, for general questions, a discussion item on: https://github.com/orgs/gempy-project/discussions

**Comment by malflink** [comment]
All good
mike
